#!/bin/bash

UNAME=$1

if [[ -z $UNAME ]]; then
	echo "Usage: get-user-key UNAME"
	exit 1
fi


/usr/bin/aws dynamodb get-item \
--region eu-west-1 \
--table-name ssh-access \
--key "{\"userid\" : {\"S\" : \"${UNAME}\"}}" \
--attributes-to-get "public-keys" \
--output text | awk -F '\t+' '{print $2}'

